version: '3'

services:
  mathapi:
    image: hojiakbaranorboyev/mathapi
    container_name: "mathapi"
    restart: always
    ports:
      - "80:5000"
    networks:
      - web

networks:
  web:
    external: true